---
chroot_libs:
  - "{{ chroot_path }}/usr/lib"
  - "{{ chroot_path }}/lib/x86_64-linux-gnu"
ansible_python_interpreter_chroot: "LD_LIBRARY_PATH='{{ chroot_libs | join(':') }}' {{ chroot_path }}/usr/bin/python3"
packages:
  - zip
  - curl
  - bash
  - python3