---
- hosts: default
  gather_facts: no
  become: true
  roles:
    - jksmth.ansible-role-chroot-tmpfs-raw

- hosts: default
  become: true
  vars:
    ansible_python_interpreter: "{{ ansible_python_interpreter_chroot }}"
  roles:
    - jksmth.ansible-role-common